USE Jurassic_Park_Practica;
GO

 ---------------------------------------------------------------
-- 1. Distrito_Escolar  [sin dependencias]
 ---------------------------------------------------------------
-- Requerido antes de Escuela (FK codigo_distrito_escolar)
INSERT INTO Distrito_Escolar (codigo_distrito_escolar, nombre_distrito_escolar) VALUES (1, 'Distrito General');;
 ---------------------------------------------------------------
-- 2. Escuela  [depende de: Distrito_Escolar]
 ---------------------------------------------------------------
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (1, 'Escuela Domingo Faustino Sarmiento', 1, 'Soler', 219);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (2, 'Instituto Santa Elena', 1, 'Las Acacias', 23);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (3, 'Escuela Nacional Nro 4 Nicolas Avellaneda', 1, 'Salvador y Nicaragua', 0);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (4, 'Escuela Tecnica El Tornillo', 1, 'Lomas de Zamora', 1);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (5, 'First Escuela Super Important', 1, 'Av. Extranjera', 2154);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (6, 'Escuela N‹ 28', 1, 'Av. Cordoba', 1234);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (7, 'Escuela N‹ 1 Pte Roque Saenz Pena', 1, 'Av. Córdoba', 1951);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (8, 'Escuela Normal N‹ 8', 1, 'La Rioja', 1042);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (9, 'Escuela Normal Superior N‹ 4 Estanislao Severo Zeballos', 1, 'Av. Rivadavia', 4950);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (10, 'Escuela Educacion Media N‹ 11', 1, 'Av. Espora y Esteban Adrogue', 0);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (11, 'La Sra. Escuela', 1, 'Av Rivadavia', 1500);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (12, 'La Mejor Escuela', 1, 'Av de Mayo', 2323);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (13, 'Escuela de Educacion Secundaria Tecnica N‹3', 1, 'El Tordo', 459);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (14, 'Escuela Tecnica N‹6 "Ing. Juan V. Passalacgua"', 1, 'Av. Adolfo Alsina', 868);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (15, 'Instituto La Salle de Flores', 1, 'Bonifacio', 2475);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (16, 'Instituto San Jose', 1, 'Juan Vucetich', 539);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (17, 'Instituto Facundo Quiroga', 1, 'El Guaycura', 836);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (18, 'Instituto Educativo Altos de Laferrere', 1, 'Fardman', 1951);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (19, 'EGB N‹ 131 Pcia. Santiago del Estero', 1, 'Alvear', 1317);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (20, 'Colegio Almafuerte', 1, 'Guemes', 61);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (21, 'Escuela Nacional Aprendetodo', 1, 'Av. Corrientes', 5628);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (22, 'Instituto Tecnologico de Datos', 1, 'Carabobo', 1265);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (23, 'Escuela Ecologica "Planeta Verde"', 1, 'Espana', 199);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (24, 'Escuela Deportiva Leonel Messi', 1, 'Gavilan', 2151);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (25, 'Instituto Jose Manuel Estrada', 1, 'Av. San Martin', 2150);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (26, 'Escuela N‹ 51', 1, 'La Calandria', 5018);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (27, 'Escuela Tecnica Pio IX', 1, 'Yapeyu', 197);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (28, 'Escuela Nicolas Avellaneda', 1, 'Palpa', 6589);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (29, 'Escuela Primaria N‹ 14 Guillermo Enrique Hudson', 1, 'Arregui', 6840);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (30, 'Colegio Buenos Aires', 1, 'Acevedo', 357);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (31, 'EscueLa De Comercio N‹ 32', 1, 'Acasusso', 4830);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (32, 'Escuela Guida Y Spano', 1, 'Ramon Falcon', 5800);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (33, 'Escuela 16 Ernesto Bavio', 1, 'Bahia Blanca', 1551);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (34, 'Escuela 35 Tecnica Lazina ', 1, 'Lope de Vega', 2115);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (35, 'Escuela Tecnica 17', 1, 'Lacarra', 535);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (36, 'Escuela N‹ 124 Luis Jorge Fontana', 1, 'Av. 25 De Mayo', 1599);
INSERT INTO Escuela (codigo_escuela, nombre_escuela, codigo_distrito_escolar, calle_escuela, altura_escuela) VALUES (37, 'Escuela Normal Superior N‹4  Estanislao S. Zeballos.', 1, 'Av. Rivadavia', 4952);

 ---------------------------------------------------------------
-- 3. Guia  [sin dependencias]
 ---------------------------------------------------------------
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (1, 'Bernardo', 'Lopez Aguado', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (2, 'Victor Manuel', 'Grondona Echague', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (3, 'Victor Hugo', 'Morales', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (4, 'Eleonora', 'Fernandez', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (5, 'Cristina', 'Zaluzi', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (6, 'Juan', 'Fernandez', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (7, 'Maria', 'Fernandez', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (8, 'Esteban', 'Quito', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (9, 'Gonzalo', 'Gimenez', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (10, 'Celeste', 'Aguirre', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (11, 'Agustin', 'Aguaysol', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (12, 'Julieta', 'Bonpetit', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (13, 'Pedro', 'Martinez', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (14, 'Adrian', 'Gomez', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (15, 'Josefina', 'Santalla', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (16, 'Marcelo', 'Kumar', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (17, 'Tomas', 'Tomassini', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (18, 'Joaquina', 'Hernandez', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (19, 'Laura', 'Acosta ', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (20, 'Liliana', 'Wainstein', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (21, 'Diego', 'De La Vega', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (22, 'Paulina', 'De La Mora', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (23, 'Lucas', 'Guinoa', 0.00, 'Sin domicilio asignado');
INSERT INTO Guia (codigo_guia, nombre_guia, apellido_guia, sueldo_hora, domicilio_guia) VALUES (24, 'Cecilia', 'Santa Cruz', 0.00, 'Sin domicilio asignado');

 ---------------------------------------------------------------
-- 4. Grado  [sin dependencias]
 ---------------------------------------------------------------
INSERT INTO Grado (codigo_grado, descripcion_grado) VALUES (1, 'Primer grado');
INSERT INTO Grado (codigo_grado, descripcion_grado) VALUES (2, 'Segundo grado');
INSERT INTO Grado (codigo_grado, descripcion_grado) VALUES (3, 'Tercer grado');
INSERT INTO Grado (codigo_grado, descripcion_grado) VALUES (4, 'Cuarto grado');
INSERT INTO Grado (codigo_grado, descripcion_grado) VALUES (5, 'Quinto grado');
INSERT INTO Grado (codigo_grado, descripcion_grado) VALUES (6, 'Sexto grado');
INSERT INTO Grado (codigo_grado, descripcion_grado) VALUES (7, 'Septimo grado');
INSERT INTO Grado (codigo_grado, descripcion_grado) VALUES (8, 'Octavo grado');
INSERT INTO Grado (codigo_grado, descripcion_grado) VALUES (9, 'Noveno grado');

 ---------------------------------------------------------------
-- 5. Tipo_Visita  [sin dependencias]
 ---------------------------------------------------------------
INSERT INTO Tipo_Visita (codigo_tipo_visita, descripcion_tipo_visita, arancel_tipo_visita) VALUES (1, 'Parque de Brontosaurios', 10);
INSERT INTO Tipo_Visita (codigo_tipo_visita, descripcion_tipo_visita, arancel_tipo_visita) VALUES (2, 'Los Mamuts en Familia', 8);
INSERT INTO Tipo_Visita (codigo_tipo_visita, descripcion_tipo_visita, arancel_tipo_visita) VALUES (3, 'Las Tortugas Prehistoricas', 4);
INSERT INTO Tipo_Visita (codigo_tipo_visita, descripcion_tipo_visita, arancel_tipo_visita) VALUES (4, 'Laguna de Nahuelito', 6);
INSERT INTO Tipo_Visita (codigo_tipo_visita, descripcion_tipo_visita, arancel_tipo_visita) VALUES (5, 'Las cenizas del meteorito mortal', 8);
INSERT INTO Tipo_Visita (codigo_tipo_visita, descripcion_tipo_visita, arancel_tipo_visita) VALUES (6, 'Visita a los huevos de mama Dino', 10);
INSERT INTO Tipo_Visita (codigo_tipo_visita, descripcion_tipo_visita, arancel_tipo_visita) VALUES (7, 'Dinos argentinos', 6);
INSERT INTO Tipo_Visita (codigo_tipo_visita, descripcion_tipo_visita, arancel_tipo_visita) VALUES (8, 'Zoo', 11);
INSERT INTO Tipo_Visita (codigo_tipo_visita, descripcion_tipo_visita, arancel_tipo_visita) VALUES (9, 'Plantas exoticas', 12);
INSERT INTO Tipo_Visita (codigo_tipo_visita, descripcion_tipo_visita, arancel_tipo_visita) VALUES (10, 'Mini exploadores, buscando dinos', 9);
INSERT INTO Tipo_Visita (codigo_tipo_visita, descripcion_tipo_visita, arancel_tipo_visita) VALUES (11, 'Jardin Botanico', 18);
INSERT INTO Tipo_Visita (codigo_tipo_visita, descripcion_tipo_visita, arancel_tipo_visita) VALUES (12, 'El mundo de Avatar', 20);
INSERT INTO Tipo_Visita (codigo_tipo_visita, descripcion_tipo_visita, arancel_tipo_visita) VALUES (13, 'Circuito de los 7 lagos', 30);
INSERT INTO Tipo_Visita (codigo_tipo_visita, descripcion_tipo_visita, arancel_tipo_visita) VALUES (14, 'ReptoSaurios', 40);
INSERT INTO Tipo_Visita (codigo_tipo_visita, descripcion_tipo_visita, arancel_tipo_visita) VALUES (15, 'Lagartos', 1);
INSERT INTO Tipo_Visita (codigo_tipo_visita, descripcion_tipo_visita, arancel_tipo_visita) VALUES (16, 'Laboratorio', 40);
INSERT INTO Tipo_Visita (codigo_tipo_visita, descripcion_tipo_visita, arancel_tipo_visita) VALUES (17, 'Museo Tiranosaurio Rex', 15);

 ---------------------------------------------------------------
-- 6. Reserva  [depende de: Escuela]
 ---------------------------------------------------------------
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (1, '20000410', '08:00:00', 1);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (2, '20010523', '09:00:00', 2);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (3, '20020614', '10:30:00', 1);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (4, '20030510', '11:00:00', 3);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (5, '20030511', '09:00:00', 4);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (6, '20030510', '09:00:00', 2);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (7, '20030510', '14:00:00', 4);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (8, '20030510', '11:00:00', 5);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (9, '20020614', '13:00:00', 1);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (10, '20200515', '12:00:00', 6);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (11, '20200501', '11:30:00', 2);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (12, '20210302', '11:20:00', 3);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (13, '20210326', '09:00:00', 11);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (14, '20210310', '10:00:00', 12);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (15, '20210410', '09:00:00', 8);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (16, '20210211', '10:30:00', 14);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (17, '20200321', '09:45:00', 21);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (18, '20200830', '13:20:00', 22);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (19, '20150904', '16:30:00', 21);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (20, '19980610', '14:15:00', 22);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (21, '20210211', '10:00:00', 30);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (22, '20010510', '14:00:00', 23);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (23, '20050525', '14:30:00', 24);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (24, '20210430', '09:00:00', 31);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (25, '20210430', '15:00:00', 32);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (26, '20210430', '15:00:00', 4);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (27, '20210429', '10:00:00', 7);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (28, '20210427', '14:50:00', 9);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (29, '20210508', '10:30:00', 36);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (30, '20210509', '14:30:00', 37);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (31, '20160818', '09:30:00', 10);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (32, '20130406', '12:00:00', 17);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (33, '20160720', '11:30:00', 16);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (34, '20120512', '11:20:00', 17);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (35, '20170913', '09:00:00', 16);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (36, '20150520', '10:00:00', 15);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (37, '20150615', '09:30:00', 16);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (38, '20140820', '08:30:00', 19);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (39, '20170417', '08:00:00', 20);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (40, '20111022', '11:00:00', 18);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (41, '20120925', '10:30:00', 28);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (42, '20160818', '09:00:00', 29);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (43, '20130410', '10:00:00', 26);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (44, '20130913', '10:00:00', 27);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (45, '20180602', '10:30:00', 25);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (46, '20100711', '11:30:00', 29);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (47, '20201218', '11:00:00', 18);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (48, '20170712', '08:30:00', 34);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (49, '20110610', '08:00:00', 33);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (50, '20150719', '12:00:00', 36);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (51, '20181201', '10:00:00', 35);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (52, '20130503', '09:00:00', 36);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (53, '20180831', '12:00:00', 10);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (54, '20121220', '12:30:00', 34);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (55, '20200508', '11:00:00', 15);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (56, '20151223', '08:00:00', 11);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (57, '20200523', '09:00:00', 1);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (58, '20140202', '10:30:00', 30);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (59, '20150131', '12:00:00', 4);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (60, '20181008', '11:30:00', 13);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (61, '20191223', '09:30:00', 5);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (62, '20151018', '08:00:00', 9);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (63, '20131125', '10:00:00', 2);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (64, '20191026', '08:30:00', 31);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (65, '20181118', '10:30:00', 36);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (66, '20160330', '11:00:00', 31);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (67, '20130326', '09:00:00', 10);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (68, '20191029', '09:30:00', 32);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (69, '20100109', '12:00:00', 14);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (70, '20140413', '10:00:00', 37);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (71, '20150719', '09:00:00', 24);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (72, '20130503', '12:00:00', 9);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (73, '20121220', '12:30:00', 24);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (74, '20190821', '11:00:00', 10);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (75, '20121206', '08:00:00', 4);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (76, '20190122', '09:00:00', 23);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (77, '20120715', '10:30:00', 21);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (78, '20181229', '12:00:00', 11);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (79, '20170214', '11:30:00', 6);
INSERT INTO Reserva (numero_reserva, fecha_reserva, hora_reserva, codigo_escuela) VALUES (80, '20151223', '09:30:00', 10);

 ---------------------------------------------------------------
-- 7. Reserva_Tipo_Visita  [depende de: Reserva, Tipo_Visita, Guia]
 ---------------------------------------------------------------
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (1, 2, 1, 25, 21);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (1, 1, 2, 30, 25);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (1, 3, 3, 110, 89);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (2, 1, 3, 56, 50);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (2, 4, 4, 90, 78);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (2, 3, 5, 100, 53);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (3, 3, 2, 21, 15);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (3, 1, 4, 42, 22);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (3, 2, 1, 54, 46);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (3, 4, 5, 110, 98);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (4, 1, 1, 120, 103);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (4, 2, 3, 130, 125);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (5, 3, 5, 114, 112);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (5, 2, 4, 95, 90);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (6, 5, 5, 65, 52);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (6, 14, 15, 37, 37);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (6, 1, 12, 93, 53);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (7, 2, 2, 210, 190);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (7, 13, 15, 57, 50);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (7, 3, 15, 44, 42);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (8, 1, 1, 25, 20);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (8, 2, 3, 32, 26);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (9, 5, 5, 70, 68);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (9, 15, 16, 67, 60);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (9, 14, 18, 70, 68);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (10, 3, 6, 80, 80);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (10, 10, 16, 89, 55);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (10, 2, 11, 83, 81);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (11, 6, 9, 30, 28);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (11, 5, 13, 87, 59);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (12, 7, 11, 45, 38);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (12, 1, 14, 91, 74);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (13, 8, 18, 109, 60);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (13, 1, 10, 107, 31);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (14, 3, 5, 72, 53);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (15, 7, 22, 45, 32);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (15, 11, 10, 108, 47);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (16, 3, 19, 68, 27);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (16, 16, 9, 55, 34);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (16, 8, 15, 48, 35);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (17, 12, 22, 98, 36);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (17, 11, 21, 300, 125);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (18, 12, 22, 132, 75);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (18, 11, 21, 54, 21);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (19, 12, 22, 67, 60);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (19, 11, 21, 140, 128);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (20, 11, 22, 78, 40);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (20, 12, 21, 29, 10);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (21, 1, 23, 30, 20);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (21, 2, 8, 25, 20);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (22, 2, 2, 80, 41);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (22, 8, 3, 75, 55);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (23, 2, 2, 50, 50);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (23, 13, 24, 100, 95);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (24, 15, 3, 49, 40);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (24, 12, 5, 91, 79);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (25, 16, 6, 28, 20);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (25, 4, 24, 102, 46);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (26, 1, 2, 67, 60);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (26, 4, 6, 92, 43);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (26, 14, 3, 106, 44);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (27, 2, 5, 43, 40);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (27, 1, 23, 81, 65);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (28, 3, 5, 23, 20);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (28, 7, 2, 62, 49);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (29, 10, 2, 40, 40);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (29, 6, 9, 86, 62);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (29, 13, 3, 63, 52);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (30, 11, 4, 30, 20);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (30, 10, 2, 89, 52);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (30, 8, 16, 78, 60);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (30, 4, 18, 68, 32);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (31, 9, 21, 95, 86);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (31, 4, 15, 102, 96);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (32, 5, 12, 86, 42);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (33, 3, 12, 77, 56);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (33, 10, 24, 100, 89);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (34, 15, 6, 90, 78);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (35, 5, 4, 100, 36);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (36, 11, 23, 97, 63);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (36, 3, 21, 95, 68);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (36, 7, 13, 79, 54);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (36, 6, 18, 105, 62);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (37, 3, 15, 84, 84);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (37, 8, 3, 78, 30);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (38, 7, 15, 109, 71);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (38, 1, 21, 77, 46);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (38, 5, 21, 104, 83);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (39, 12, 5, 92, 75);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (40, 17, 16, 103, 43);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (40, 12, 6, 108, 72);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (41, 10, 15, 102, 102);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (41, 15, 13, 49, 45);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (42, 7, 22, 103, 50);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (43, 13, 23, 105, 28);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (44, 6, 16, 81, 75);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (44, 16, 24, 71, 38);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (45, 17, 11, 76, 57);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (45, 6, 24, 97, 94);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (45, 7, 8, 91, 63);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (46, 13, 1, 56, 51);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (47, 1, 5, 59, 42);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (47, 13, 18, 97, 62);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (48, 7, 19, 78, 27);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (49, 2, 12, 86, 27);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (49, 10, 12, 67, 34);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (50, 7, 8, 83, 60);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (51, 9, 16, 67, 44);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (52, 10, 12, 52, 37);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (52, 5, 16, 102, 67);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (52, 6, 22, 54, 53);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (53, 5, 4, 39, 35);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (54, 8, 6, 45, 37);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (54, 17, 14, 36, 32);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (55, 4, 21, 51, 48);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (55, 6, 8, 55, 30);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (56, 4, 7, 44, 42);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (57, 13, 23, 83, 37);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (58, 17, 23, 96, 33);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (58, 3, 7, 108, 54);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (58, 12, 15, 71, 54);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (59, 7, 4, 82, 39);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (60, 17, 1, 56, 32);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (60, 15, 23, 53, 51);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (61, 11, 8, 88, 30);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (62, 8, 11, 58, 44);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (63, 15, 13, 85, 37);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (63, 5, 14, 58, 33);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (64, 1, 9, 37, 28);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (65, 15, 16, 93, 84);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (65, 12, 24, 109, 32);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (66, 6, 8, 80, 51);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (67, 15, 5, 96, 55);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (68, 1, 15, 62, 53);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (69, 4, 2, 44, 30);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (70, 16, 10, 106, 44);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (70, 9, 23, 67, 28);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (70, 8, 4, 65, 35);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (71, 8, 19, 41, 33);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (72, 6, 5, 104, 28);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (72, 10, 2, 110, 84);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (73, 16, 23, 66, 44);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (73, 1, 12, 58, 43);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (73, 10, 3, 79, 44);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (73, 4, 16, 31, 31);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (74, 12, 1, 88, 43);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (75, 2, 10, 54, 32);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (75, 7, 4, 27, 27);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (75, 17, 15, 59, 31);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (76, 15, 15, 103, 100);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (77, 9, 1, 95, 47);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (77, 1, 15, 61, 25);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (78, 11, 23, 99, 50);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (78, 13, 13, 60, 47);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (78, 1, 13, 106, 68);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (79, 4, 18, 33, 33);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (80, 2, 18, 109, 104);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (80, 4, 16, 60, 55);
INSERT INTO Reserva_Tipo_Visita (numero_reserva, codigo_tipo_visita, codigo_guia, cantidad_alumnos_reservados, cantidad_alumnos_reales) VALUES (80, 10, 4, 105, 96);

 ---------------------------------------------------------------
-- 8. Reserva_Por_Grado  [depende de: Reserva_Tipo_Visita, Grado]
 ---------------------------------------------------------------
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (1, 2, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (1, 1, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (1, 5, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (1, 6, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (1, 3, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (1, 7, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (2, 5, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (2, 7, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (2, 7, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (2, 4, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (3, 4, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (3, 1, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (3, 2, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (3, 5, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (4, 4, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (4, 3, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (5, 6, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (5, 5, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (6, 5, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (6, 6, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (6, 5, 5);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (6, 6, 14);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (7, 1, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (7, 2, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (7, 3, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (7, 1, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (7, 2, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (7, 3, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (7, 1, 13);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (7, 2, 13);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (7, 3, 13);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (8, 3, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (8, 4, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (9, 5, 5);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (9, 7, 5);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (9, 5, 14);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (9, 6, 14);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (9, 6, 15);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (9, 7, 15);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (10, 2, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (10, 6, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (10, 1, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (10, 2, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (10, 4, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (11, 1, 5);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (11, 5, 5);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (11, 3, 6);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (12, 4, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (12, 2, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (12, 6, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (13, 2, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (13, 8, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (13, 1, 8);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (13, 2, 8);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (14, 4, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (14, 5, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (15, 4, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (15, 6, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (15, 6, 11);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (15, 7, 11);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (16, 1, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (16, 3, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (16, 1, 8);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (16, 4, 8);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (16, 2, 16);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (16, 3, 16);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (17, 1, 11);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (17, 7, 12);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (18, 5, 11);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (18, 2, 12);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (19, 3, 11);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (19, 5, 11);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (19, 3, 12);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (19, 5, 12);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (20, 6, 11);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (20, 4, 12);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (21, 6, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (21, 7, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (21, 4, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (22, 1, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (22, 5, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (22, 4, 8);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (23, 2, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (23, 3, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (23, 4, 13);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (23, 7, 13);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (24, 2, 12);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (24, 4, 15);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (24, 7, 15);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (25, 1, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (25, 6, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (25, 5, 16);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (25, 7, 16);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (26, 1, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (26, 3, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (26, 2, 14);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (26, 7, 14);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (27, 2, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (27, 3, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (27, 5, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (28, 1, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (28, 1, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (28, 5, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (29, 4, 6);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (29, 3, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (29, 7, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (29, 4, 13);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (29, 7, 13);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (30, 1, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (30, 6, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (30, 1, 8);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (30, 5, 8);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (30, 3, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (30, 6, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (30, 5, 11);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (31, 1, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (31, 5, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (31, 1, 9);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (31, 6, 9);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (32, 1, 5);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (32, 3, 5);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (33, 4, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (33, 7, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (33, 2, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (33, 3, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (34, 3, 15);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (34, 5, 15);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (35, 4, 5);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (35, 7, 5);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (36, 3, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (36, 5, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (36, 2, 6);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (36, 3, 6);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (36, 2, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (36, 4, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (36, 4, 11);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (36, 5, 11);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (37, 5, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (37, 7, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (37, 1, 8);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (37, 5, 8);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (38, 1, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (38, 7, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (38, 4, 5);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (38, 6, 5);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (38, 1, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (38, 2, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (39, 5, 12);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (40, 5, 12);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (40, 6, 12);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (40, 2, 17);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (40, 4, 17);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (41, 2, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (41, 5, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (41, 2, 15);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (41, 4, 15);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (42, 2, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (43, 1, 13);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (43, 4, 13);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (44, 1, 6);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (44, 5, 6);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (44, 1, 16);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (44, 2, 16);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (45, 4, 6);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (45, 5, 6);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (45, 1, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (45, 3, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (45, 2, 17);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (45, 6, 17);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (46, 2, 13);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (46, 7, 13);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (47, 1, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (47, 7, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (47, 3, 13);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (47, 6, 13);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (48, 3, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (48, 4, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (49, 1, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (49, 4, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (49, 3, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (49, 5, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (50, 2, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (50, 3, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (51, 2, 9);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (51, 6, 9);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (52, 2, 5);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (52, 5, 5);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (52, 1, 6);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (52, 3, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (52, 7, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (53, 7, 5);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (54, 1, 8);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (54, 4, 8);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (54, 2, 17);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (54, 7, 17);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (55, 4, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (55, 6, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (55, 7, 6);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (56, 2, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (56, 3, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (57, 1, 13);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (57, 7, 13);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (58, 1, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (58, 3, 3);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (58, 7, 12);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (58, 1, 17);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (58, 2, 17);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (59, 5, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (59, 7, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (60, 1, 15);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (60, 2, 15);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (60, 6, 15);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (60, 1, 17);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (60, 2, 17);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (61, 5, 11);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (61, 7, 11);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (62, 1, 8);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (62, 6, 8);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (63, 1, 5);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (63, 5, 5);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (63, 6, 5);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (63, 4, 15);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (63, 6, 15);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (64, 5, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (64, 7, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (65, 5, 12);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (65, 6, 12);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (65, 2, 15);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (65, 6, 15);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (66, 1, 6);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (66, 3, 6);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (67, 1, 15);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (67, 2, 15);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (68, 2, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (68, 5, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (69, 4, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (69, 5, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (70, 2, 8);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (70, 5, 8);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (70, 4, 9);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (70, 2, 16);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (70, 3, 16);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (71, 3, 8);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (71, 5, 8);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (72, 2, 6);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (72, 3, 6);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (72, 1, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (72, 2, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (72, 4, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (73, 3, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (73, 7, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (73, 2, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (73, 6, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (73, 2, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (73, 4, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (73, 1, 16);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (73, 2, 16);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (74, 1, 12);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (74, 3, 12);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (75, 7, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (75, 9, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (75, 2, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (75, 7, 7);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (75, 1, 17);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (75, 2, 17);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (76, 3, 15);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (76, 5, 15);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (77, 4, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (77, 7, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (77, 4, 9);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (77, 7, 9);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (78, 2, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (78, 5, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (78, 7, 1);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (78, 7, 11);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (78, 2, 13);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (79, 5, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (79, 4, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (80, 5, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (80, 6, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (80, 7, 2);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (80, 5, 4);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (80, 6, 10);
INSERT INTO Reserva_Por_Grado (numero_reserva, codigo_grado, codigo_tipo_visita) VALUES (80, 7, 10);

 ---------------------------------------------------------------
